DATES:
  TRAIN:
    START_DATE : "2000-01-01"
    END_DATE : "2022-11-30"
  VAL:
    START_DATE : "2021-08-01"
    END_DATE : "2021-11-30"
  TEST:
    START_DATE : "2021-12-01"
    END_DATE : "2023-07-01"
  
SYMBOLS: ["SPY"]

INDICATORS : 
  TECHNICAL : [
    "macd",
    "boll_ub",
    "boll_lb",
    "rsi_30",
    "cci_30",
    "dx_30",
    "close_30_sma",
    "close_60_sma",
  ]
  FUNDAMENTAL : [
    "2year_rate",
    "10year_rate",
    "30year_rate",
    "vix"
    # "earnings",
  ]

# parameters for data sources
API_KEYS:
  ALPHA_VANTAGE : "BMUKDHLNVBEVBUKT"

URLS:
  FUNDAMENTAL_DATA: 'https://www.alphavantage.co/query?function={function}&symbol={symbol}&apikey={key}'
  TREASURY_DATA: 'https://www.alphavantage.co/query?function=TREASURY_YIELD&interval={interval}&maturity={maturity}&apikey={key}'
  TIME_SERIES_DATA: 'https://www.alphavantage.co/query?function={function}&symbol={symbol}&interval={interval}&apikey={key}&outputsize=full'

PPO_PARAMS : {
    "ppo":{
        "n_steps": 2048,
        "ent_coef": 0.005,
        "learning_rate": 0.0002, #0.001 for multi stock portfolio weight
        "batch_size": 128,
        "gamma": 0.99, #.9999 for longer rewards
        }
    }

# # Model Parameters
# A2C_PARAMS : {"n_steps": 5, "ent_coef": 0.01, "learning_rate": 0.0007}