DATES:
  TRAIN:
    START_DATE : "2006-01-01"
    END_DATE : "2014-12-31"
  VAL:
    START_DATE : "2021-08-01"
    END_DATE : "2021-11-30"
  TEST:
    START_DATE : "2021-12-01"
    END_DATE : "2023-07-01"
  
# SYMBOLS: ["NVDA", "AAPL", "META", "IBM"]
SYMBOLS: ["SPY"]
# SYMBOLS: ["SPY"]

INDICATORS : 
  TECHNICAL : [
    "macd",
    "boll_ub",
    "boll_lb",
    "rsi_30",
    "cci_30",
    "dx_30",
    "close_30_sma",
    "close_60_sma",
  ]
  FUNDAMENTAL : [
    "2year_rate",
    "10year_rate",
    "30year_rate",
    "vix"
    # "earnings",
  ]

# parameters for data sources
API_KEYS:
  ALPHA_VANTAGE : "BMUKDHLNVBEVBUKT"

URLS:
  FUNDAMENTAL_DATA: 'https://www.alphavantage.co/query?function={function}&symbol={symbol}&apikey={key}'
  TREASURY_DATA: 'https://www.alphavantage.co/query?function=TREASURY_YIELD&interval={interval}&maturity={maturity}&apikey={key}'
  TIME_SERIES_DATA: 'https://www.alphavantage.co/query?function={function}&symbol={symbol}&interval={interval}&apikey={key}&outputsize=full'

PPO_PARAMS : {
    "ppo":{
        "n_steps": 2048,
        "ent_coef": 0.005,
        "learning_rate": 0.0003, #0.001 for multi stock portfolio weight
        "batch_size": 128,
        "gamma": 0.9999, #.9999 for longer rewards
        }
    }

# DATA_SAVE_DIR : "datasets"
# TRAINED_MODEL_DIR : "trained_models"
# TENSORBOARD_LOG_DIR : "tensorboard_log"
# RESULTS_DIR : "results"



# # Model Parameters
# A2C_PARAMS : {"n_steps": 5, "ent_coef": 0.01, "learning_rate": 0.0007}
# PPO_PARAMS : {
#     "n_steps": 2048,
#     "ent_coef": 0.01,
#     "learning_rate": 0.00025,
#     "batch_size": 64,
# }
# DDPG_PARAMS : {"batch_size": 128, "buffer_size": 50000, "learning_rate": 0.001}
# TD3_PARAMS : {"batch_size": 100, "buffer_size": 1000000, "learning_rate": 0.001}
# SAC_PARAMS : {
#     "batch_size": 64,
#     "buffer_size": 100000,
#     "learning_rate": 0.0001,
#     "learning_starts": 100,
#     "ent_coef": "auto_0.1",
# }
# ERL_PARAMS : {
#     "learning_rate": 3e-5,
#     "batch_size": 2048,
#     "gamma": 0.985,
#     "seed": 312,
#     "net_dimension": 512,
#     "target_step": 5000,
#     "eval_gap": 30,
#     "eval_times": 64,
# }
# RLlib_PARAMS : {"lr": 5e-5, "train_batch_size": 500, "gamma": 0.99}


# # Possible time zones
# TIME_ZONE_SHANGHAI : "Asia/Shanghai"  # Hang Seng HSI, SSE, CSI
# TIME_ZONE_USEASTERN : "US/Eastern"  # Dow, Nasdaq, SP
# TIME_ZONE_PARIS : "Europe/Paris"  # CAC,
# TIME_ZONE_BERLIN : "Europe/Berlin"  # DAX, TECDAX, MDAX, SDAX
# TIME_ZONE_JAKARTA : "Asia/Jakarta"  # LQ45
# TIME_ZONE_SELFDEFINED : "xxx"  # If neither of the above is your time zone, you should define it, and set USE_TIME_ZONE_SELFDEFINED 1.
# USE_TIME_ZONE_SELFDEFINED : 0  # 0 (default) or 1 (use the self defined)